#! /usr/bin/env perl

use Error qw(:try);
use Error::Simple;
use Getopt::Long qw(:config no_ignore_case);
use sigtrap qw/handler signal_handler INT TERM/;
use Sys::Hostname;

use strict;

#Define application-specific web server handling
{
    package WebServer;
    use HTTP::Server::Simple::CGI;
    use Sys::Hostname;
    use base qw(HTTP::Server::Simple::CGI);

    my %dispatch = (
        "/" => \&motd,
        "/deposit" => \&get_deposit
    );
    my $llogs = 0;

    sub motd {
        my ($cgi) = @_;
        print(STDOUT "HTTP/1.0 200 OK\n");
        print(STDOUT $cgi->header);
        print(STDOUT $cgi->start_html("Welcome."));
        print(STDOUT $cgi->h1("This is the message of the day."));
        print(STDOUT $cgi->end_html);
        return 0;
    }

    sub cleanup {
        my ($cgi) = @_;
        print(STDOUT "HTTP/1.0 200 OK\n");
        print(STDOUT $cgi->header);
        print(STDOUT $cgi->start_html("Shutdown request received."));
        print(STDOUT $cgi->end_html);
        kill(-15, $$);
        kill(-15, getppid());
        exit 0;
    }

    sub get_deposit {
        my ($cgi) = @_;
        my @contents = $cgi->param("DEPOSIT");
        open(DEPOSIT, ">>", "deposit-log");
        foreach my $content (@contents) { print(DEPOSIT "$content\n"); }
        close(DEPOSIT);
        print(STDOUT "HTTP/1.0 200 OK\n");
        print(STDOUT $cgi->header);
        print(STDOUT $cgi->start_html("Log received."));
        print(STDOUT $cgi->end_html);
        return 0;
    }

    sub handle_request {
        my ($self, $cgi) = @_;
        my $path = $cgi->path_info();
        my $handler = $dispatch{$path};
        if(ref($handler) eq "CODE") { $handler->($cgi); }
        else {
            print(STDOUT "HTTP/1.0 404 Not found\n");
            print(STDOUT $cgi->header);
            print(STDOUT $cgi->start_html("Not found."));
            print(STDOUT $cgi->end_html);
        }
        return 0;
    }
}

my $usage = "Log Deposit Receiver Options:

Required:

Optional:

    --help                  Display this message.

Example Usage:

    perl deposit-receiver

";

my %OPT;
try {
    GetOptions(
        "port=s" => \$OPT{port},
        "help|?" => sub { print $usage; exit(0); },
    );
}
catch Error::Simple with {
    my $E = shift;
    print STDERR $E->{-text};
    die "Failed to parse command line options.\n";
};

my $client = 0;
my $err = 0;
my $port = $OPT{port};
if(!$port) { $port = 9000; }
if($err) {
    print(STDERR "Could not find $err required arguments.\n");
    print_help();
}

my $host = hostname();
my $server = WebServer->new(11855);
print(STDOUT "Server established at $host:11855.\n\n");
$server->run();
exit(0);

sub signal_handler {
    print(STDERR "\nCaught '$!' signal. Terminating process.\n");
    exit(1);
}

sub print_help {
    print(STDOUT $usage);
    exit(1);
}

# vim: tabstop=8 shiftwidth=4 softtabstop=4 expandtab shiftround autoindent
