#!/bin/sh

homehost=$1
shift
homeport=$1
shift
sysuuid="$1"
shift
dir="$1"
shift
home="$homehost:$homeport"
puuid=$TLQPARENTUUID
if [ "$puuid" = "" ]; then
    puuid="$sysuuid"
fi
hostname=$(hostname -f)

declare -a logs
declare -a types
declare -a finals
proc=$(ps -AF | grep "tlq-server" | head -1 | awk '{print $2}')
port=$(netstat -tlpn 2> /dev/null | grep "$proc/perl" | tail -1 | awk '{print $4}' | cut -d ":" -f 2)
if [ "$port" = "" ]; then
    let port="11855"
fi
i=0
j=0
for arg in "$@"
do
    if [ "$arg" = "--" ]; then
        shift
        break
    fi
    if [ `expr $j % 2` -eq 0 ]; then
        logs[$i]="$arg"
        let j="j+1"
    else
        types[$i]="$arg"
        let i="i+1"
        let j="j+1"
    fi
    shift
done
cmd=$@
cuuid=$(uuidgen)
if [ ! -d $dir ]; then
    errmsg="Command $cmd aborted at $hostname. No TLQ log server running at working directory $dir."
    curl --data-urlencode "DEPOSIT=$errmsg" http://$home/deposit > /dev/null
    exit 1
fi
TLQPARENTUUID="$cuuid"
uri="http://$hostname:$port/components/$cuuid"
j=0
for log in "${logs[@]}"
do
    logtype=${types[j]}
    loguuid=$(uuidgen)
    exists=$(grep "$log")
    flag=0
    if [ "$exists" ]; then
        let flag=1
        finals[$j]="$log"
    else
        finals[$j]="$dir/${loguuid}.log"
    fi
    cmd="${cmd//$log/$dir/${loguuid}.log}"
    echo "$cuuid $log $logtype $loguuid $flag $cmd" >> "$dir/deposit-log"
    deposit="Component $cuuid created log $log with command $cmd queryable at $uri."
    curl --data-urlencode "DEPOSIT=$deposit" http://$home/deposit > /dev/null
    echo $deposit
    let j="j+1"
done

$cmd
result=$?
for log in "${finals[@]}"
do
    echo "Component $cuuid created log $log with command $cmd queryable at $uri." >> $log
done
exit $result
