#!/bin/sh

homehost=$1
shift
homeport=$1
shift
sysuuid="$1"
shift
home="$homehost:$homeport"
puuid=$TLQPARENTUUID
if [ "$puuid" = "" ]; then
    puuid="$sysuuid"
fi
dir=/tmp/logquery
hostname=$(hostname -f)
declare -a logs
declare -a types
proc=$(ps -AF | grep "logserver" | head -1 | awk '{print $2}')
port=$(netstat -tlpn 2> /dev/null | grep "$proc/perl" | tail -1 | awk '{print $4}' | cut -d ":" -f 2)
if [ "$port" = "" ]; then
    let port="11855"
fi
i=0
j=0
for arg in "$@"
do
    if [ "$arg" = "--" ]; then
        shift
        break
    fi
    if [ `expr $j % 2` -eq 0 ]; then
        logs[$i]="$arg"
        let j="j+1"
    else
        types[$i]="$arg"
        let i="i+1"
        let j="j+1"
    fi
    shift
done
cmd=$@
j=0
for log in "${logs[@]}"
do
    logtype=${types[j]}
    loghash=$(uuidgen)
    echo "$sysuuid $log $logtype $loghash" >> "$dir/deposit-log"
    let j="j+1"
done

cid=$(uuidgen)
TLQPARENTUUID="$cid"
uri="http://$hostname:$port/$cid"
deposit="Component $cid created log(s) [${logs[*]}] with command $cmd queryable at $uri and has parent $puuid."
curl --data-urlencode "DEPOSIT=$deposit" http://$home/deposit

result=exec $cmd
exit $result
