#!/bin/sh

sysname=$1
shift
topuuid=$1
shift
parentuuid=$TLQPARENTUUID
if [ "$parentuuid" = "" ]; then
    let parentuuid="$topuuid"
fi
echo "$topuuid $parentuuid"
dir=/tmp/logquery
hostname=$(hostname -f)
declare -a logs
declare -a types
proc=$(ps -AF | grep "logserver" | head -1 | awk '{print $2}')
port=$(netstat -tlpn 2> /dev/null | grep "$proc/perl" | tail -1 | awk '{print $4}' | cut -d ":" -f 2)
if [ "$port" = "" ]; then
    let port="11855"
fi
i=0
j=0
for arg in "$@"
do
    if [ "$arg" = "--" ]; then
        shift
        break
    fi
    if [ `expr $j % 2` -eq 0 ]; then
        logs[$i]="$arg"
        let j="j+1"
    else
        types[$i]="$arg"
        let i="i+1"
        let j="j+1"
    fi
    shift
done
cmd=$@
j=0
for log in "${logs[@]}"
do
    logtype=${types[j]}
    loghash=`echo "$sysname $log $host:$port" | md5sum | cut -d " " -f 1`
    echo "$sysname $log $logtype $loghash" >> "$dir/deposit-log"
    let j="j+1"
    echo "Log '$log' has type '$logtype' from system '$sysname' running '$cmd' with ID '$loghash' at '$hostname:$port' log watcher."
    TLQPARENTUUID="$loghash"
done
result=exec $cmd
echo "$TLQPARENTUUID"
exit $result
