#! /usr/bin/env perl

use Error qw(:try);
use Error::Simple;
use Getopt::Long qw(:config no_ignore_case);
use strict;

my $usage = "Single-Node Transfer Cost Modeling Options:

Required:

Optional:
    --datasize,-d    <integer>   Set total size of log data (in MB).
    --maxspeed,-m    <integer>   Set the maximum transfer speed (in MB/s).

    --help                  Display this message.

Example Usage:

    perl model-node --netspeed 100 --datasize 1000

";

my %OPT;
try {
    GetOptions(
        "datasize=s" => \$OPT{datasize},
        "maxspeed=s" => \$OPT{maxspeed},
        "help|?" => sub { print $usage; exit(0); },
    );
}
catch Error::Simple with {
    my $E = shift;
    print STDERR $E->{-text};
    die "Failed to parse command line options.\n";
};

my $datasize = $OPT{datasize};
my $maxspeed = $OPT{maxspeed};
if(!$datasize) { $datasize = 1000; }
if(!$maxspeed) { $maxspeed = 100; }

my $i = 0;
my $throughput;
while($i <= $datasize) {
    if($i > $maxspeed) { $throughput = $maxspeed; }
    else { $throughput = $i; }
    print(STDOUT "$i $throughput\n");
    $i++;
}

exit(0);

sub print_help {
    print(STDERR $usage);
    exit(1);
}

# vim: tabstop=8 shiftwidth=4 softtabstop=4 expandtab shiftround autoindent
