#! /usr/bin/env perl

use Error qw(:try);
use Error::Simple;
use Getopt::Long qw(:config no_ignore_case);
use strict;

my $usage = "Single-Node Transfer Cost Modeling Options:

Required:

Optional:
    --datasize,-d    <integer>   Set total size of log data (in MB).
    --maxspeed,-m    <integer>   Set the maximum transfer speed (in MB/s).

    --help                  Display this message.

Example Usage:

    perl model-node --netspeed 100 --datasize 1000

";

my %OPT;
try {
    GetOptions(
        "datasize=s" => \$OPT{datasize},
        "maxspeed=s" => \$OPT{maxspeed},
        "help|?" => sub { print $usage; exit(0); },
    );
}
catch Error::Simple with {
    my $E = shift;
    print STDERR $E->{-text};
    die "Failed to parse command line options.\n";
};

my $datasize = $OPT{datasize};
my $maxspeed = $OPT{maxspeed};
if(!$datasize) { $datasize = 100000; }
if(!$maxspeed) { $maxspeed = 100; }


my $i = 0;
my $jobs = 0;
my $jobtime = 3;
my $bandwidth = $maxspeed;
my $maxjobs = 50;
my $throughput = 0;
while($i <= $datasize) {
    if($bandwidth > 0 and $jobs < $maxjobs) {
        $jobs++;
    }
    if($i % 3 == 0 and $jobs > 0) {
        $bandwidth++;
        $jobs--;
    }
    if($bandwidth != 0) { $bandwidth--; }
    #if($i > 0) { $throughput = ($jobs / $i); }
    #if(($i / $maxspeed) > $maxspeed and ($jobs / $i) > $maxspeed) { $throughput = $maxspeed; }
    #elsif($i == 0) { $throughput = $jobs; }
    #else { $throughput = $jobs / $i; }
    
    print(STDOUT "$i $bandwidth $jobs\n");
    $i++;
}

exit(0);

sub print_help {
    print(STDERR $usage);
    exit(1);
}

# vim: tabstop=8 shiftwidth=4 softtabstop=4 expandtab shiftround autoindent
