#!/bin/sh

#Parse arguments
declare -a args
i=0
for arg in "$@"
do
    args[$i]="$arg"
    let i="i+1"
    shift
done
host=${args[0]}
port=${args[1]}
uuid=${args[2]}
dir=${args[3]}
frame=${args[4]}
log=${args[5]}
logstring=${args[6]}
ltrace=${args[7]}
ltracestring=${args[8]}
povray=${args[9]}
input=${args[10]}
output=${args[11]}
count=${args[12]}
height=${args[13]}
width=${args[14]}
debug=${args[15]}
localtrace=${args[16]}

/usr/bin/sh log-define $host $port $uuid $dir $log $logstring $ltrace $ltracestring -- ./ltrace-wrapper-condor $frame $povray +I$input +O$output +K$count +H$height +w$width +GA$debug > log-deposit.$frame\.out ; mv $debug $log ; mv $localtrace $ltrace

exit
