#!/bin/sh

#Parse arguments
declare -a args
i=0
for arg in "$@"
do
    args[$i]="$arg"
    let i="i+1"
    shift
done
host=${args[0]}
port=${args[1]}
uuid=${args[2]}
frame=${args[3]}
log=${args[4]}
logstring=${args[5]}
ltrace=${args[6]}
ltracestring=${args[7]}
povray=${args[8]}
input=${args[9]}
output=${args[10]}
count=${args[11]}
height=${args[12]}
width=${args[13]}
debug=${args[14]}
localtrace=${args[15]}

/usr/bin/sh log-define $host $port $uuid $log $logstring $ltrace $ltracestring -- ./ltrace-wrapper-condor $frame $povray +I$input +O$output +K$count +H$height +w$width +GA$debug > log-deposit.$frame\.out ; mv $debug $log ; mv $localtrace $ltrace

exit
